version: '3'

services:

    db-posts:
        container_name: db-posts
        image: postgres:12
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: jibberjabber
            POSTGRES_PASSWORD: jibberjabber
            POSTGRES_DB: jibberjabberdb_posts
        volumes:
            - postData:/var/lib/postgresql/data

    jj-posts:
        container_name: jj-posts
        image: docker.pkg.github.com/jj-services/jj-post-service/dev-jj-post-service:latest
        ports:
            - 8082:8080
        environment:
            DB_USER: jibberjabber
            DB_PASSWORD: jibberjabber
            DB_NAME: jibberjabberdb_posts
            DB_HOST: db-posts
            DB_PORT: 5432
        depends_on:
            - db-posts


    db-users:
        container_name: postgres_db2
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: jibberjabber
            POSTGRES_PASSWORD: jibberjabber
            POSTGRES_DB: jibberjabberdb
        volumes:
            - pgdata:/var/lib/postgresql/data

    jj-user:
        container_name: jj-user
        image: docker.pkg.github.com/jj-services/jj-user-service/dev-jj-user-service:latest
        ports:
            - 8081:8080
        environment:
            DB_USER: jibberjabber
            DB_PASSWORD: jibberjabber
            DB_NAME: jibberjabberdb
            DB_HOST: postgres_db
            DB_PORT: 5432
        depends_on:
            - db-users
            
    jj-message:
        container_name: jj-message
        image: docker.pkg.github.com/tomasgp97/jj-message-service/dev-jj-message-service:latest
        ports:
            - 8083:8080
        environment:
            DB_USER: jibberjabber
            DB_PASSWORD: jibberjabber
            DB_NAME: jibberjabberdb_messages
            DB_HOST: db-message
            DB_PORT: 5432
        depends_on:
            - db-message
      
    db-message:
        container_name: db-message
        image: postgres:12
        ports:
            - 5436:5432
        environment:
            POSTGRES_USER: jibberjabber
            POSTGRES_PASSWORD: jibberjabber
            POSTGRES_DB: jibberjabberdb_messages
        volumes:
            - msgData:/var/lib/postgresql/data
          
    client:
        container_name: jibber-jabber-client
        image: docker.pkg.github.com/matiasferron/jj-front/dev-jj-fe:latest
        depends_on:
            - jj-user
            - jj-posts

    nginx:
        image: nginx:1.15-alpine
        restart: unless-stopped
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - client
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        depends_on:
            - client

volumes:
    postData:
    pgdata:
    msgData:
